name: Build

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew make makePluginsJson

      - name: Upload OlaMovies
        uses: actions/upload-artifact@v4
        with:
          name: OlaMovies
          path: "**/*.cs3"
